{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe58ade1-1233-4310-871e-0c92bbdf8b22",
   "metadata": {},
   "outputs": [],
   "source": [
    "[build]\n",
    "  publish = \"build\" # Replace \"build\" with your actual build directory (e.g., \"dist\" or \"public\")\n",
    "  command = \"npm run build\" # Or the correct build command for your project\n",
    "\n",
    "[[redirects]]\n",
    "  from = \"/*\"\n",
    "  to = \"/index.html\"\n",
    "  status = 200\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
